In [1]:
import os

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

/home/lilinhan/workspace/software/anaconda/envs/tensorflow/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print tf.__version__

1.4.1


In [3]:
##################################

In [3]:
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
config = tf.ConfigProto(log_device_placement=True)
config.gpu_options.per_process_gpu_memory_fraction = 0.1

In [5]:
##################################

In [6]:
# 首先在考察 默认图

In [7]:
tf.get_default_graph(), tf.get_default_session()

(<tensorflow.python.framework.ops.Graph at 0x7fe3c82fd310>, None)

In [8]:
g0 = tf.get_default_graph()

In [9]:
t1 = tf.constant([1], dtype=tf.int32)
var1 = tf.get_variable("var1", dtype=tf.int32, shape=[2], initializer=tf.zeros_initializer)
with tf.name_scope("ns_layer1") as scope1:
    t2 = tf.constant([1], dtype=tf.int32)
    var2 = tf.get_variable("var2", dtype=tf.int32, shape=[2], initializer=tf.zeros_initializer)

with tf.variable_scope("vs_layer1") as scope2:
    t3 = tf.constant([1], dtype=tf.int32)
    var4 = tf.get_variable("var3", dtype=tf.int32, shape=[2], initializer=tf.zeros_initializer)

with tf.name_scope("ns_layer2") as scope3:
    with tf.variable_scope("ns_layer2_vs_layer1") as scope4:
        t4 = tf.constant([1], dtype=tf.int32)
        var4 = tf.get_variable("var4", dtype=tf.int32, shape=[2], initializer=tf.zeros_initializer)

with tf.variable_scope("vs_layer2") as scope5:
    with tf.name_scope("vs_layer2_ns_layer1") as scope6:
        t5 = tf.constant([1], dtype=tf.int32)
        var5 = tf.get_variable("var5", dtype=tf.int32, shape=[2], initializer=tf.zeros_initializer)


In [10]:
g0.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'var1/Initializer/zeros' type=Const>,
 <tf.Operation 'var1' type=VariableV2>,
 <tf.Operation 'var1/Assign' type=Assign>,
 <tf.Operation 'var1/read' type=Identity>,
 <tf.Operation 'ns_layer1/Const' type=Const>,
 <tf.Operation 'var2/Initializer/zeros' type=Const>,
 <tf.Operation 'var2' type=VariableV2>,
 <tf.Operation 'var2/Assign' type=Assign>,
 <tf.Operation 'var2/read' type=Identity>,
 <tf.Operation 'vs_layer1/Const' type=Const>,
 <tf.Operation 'vs_layer1/var3/Initializer/zeros' type=Const>,
 <tf.Operation 'vs_layer1/var3' type=VariableV2>,
 <tf.Operation 'vs_layer1/var3/Assign' type=Assign>,
 <tf.Operation 'vs_layer1/var3/read' type=Identity>,
 <tf.Operation 'ns_layer2/ns_layer2_vs_layer1/Const' type=Const>,
 <tf.Operation 'ns_layer2_vs_layer1/var4/Initializer/zeros' type=Const>,
 <tf.Operation 'ns_layer2_vs_layer1/var4' type=VariableV2>,
 <tf.Operation 'ns_layer2_vs_layer1/var4/Assign' type=Assign>,
 <tf.Operation 'ns_layer2_vs_laye

In [11]:
g0.collections

['variables', ('__variable_store',), ('__varscope',), 'trainable_variables']

In [12]:
g0.get_all_collection_keys()

['variables', 'trainable_variables']

In [13]:
g0.get_collection("variables")

[<tf.Variable 'var1:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'var2:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'vs_layer1/var3:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'ns_layer2_vs_layer1/var4:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'vs_layer2/var5:0' shape=(2,) dtype=int32_ref>]

In [15]:
g0.get_collection("variables", scope="vs_layer2")

[<tf.Variable 'vs_layer2/var5:0' shape=(2,) dtype=int32_ref>]

In [16]:
g0.get_collection("trainable_variables")

[<tf.Variable 'var1:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'var2:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'vs_layer1/var3:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'ns_layer2_vs_layer1/var4:0' shape=(2,) dtype=int32_ref>,
 <tf.Variable 'vs_layer2/var5:0' shape=(2,) dtype=int32_ref>]

In [18]:
g0.get_collection("trainable_variables", scope="vs_layer1")

[<tf.Variable 'vs_layer1/var3:0' shape=(2,) dtype=int32_ref>]

In [28]:
t1

<tf.Tensor 'Const:0' shape=(1,) dtype=int32>

In [29]:
g0.get_tensor_by_name("Const:0")

<tf.Tensor 'Const:0' shape=(1,) dtype=int32>

In [30]:
# 在最外层增加一个constant，看名称的变化
t6 = tf.constant([1], dtype=tf.int32)

In [31]:
t6

<tf.Tensor 'Const_1:0' shape=(1,) dtype=int32>

In [34]:
# 自定义名称
t7 = tf.constant([1], dtype=tf.int32, name="t7")

In [35]:
t7

<tf.Tensor 't7:0' shape=(1,) dtype=int32>

In [36]:
t8 = tf.constant([1], dtype=tf.int32, name="t8")

In [37]:
t8

<tf.Tensor 't8:0' shape=(1,) dtype=int32>

In [38]:
t9 = tf.constant([1], dtype=tf.int32, name="t8")

In [39]:
t9

<tf.Tensor 't8_1:0' shape=(1,) dtype=int32>

In [42]:
a = g0.get_operation_by_name("vs_layer1/Const")

In [53]:
a.outputs, a.inputs

([<tf.Tensor 'vs_layer1/Const:0' shape=(1,) dtype=int32>],
 <tensorflow.python.framework.ops._InputList at 0x7f437f53eb10>)

In [44]:
b = g0.get_operation_by_name("vs_layer1/var3/Assign")

In [45]:
b.outputs

[<tf.Tensor 'vs_layer1/var3/Assign:0' shape=(2,) dtype=int32_ref>]

In [46]:
c = g0.get_operation_by_name("vs_layer1/var3/read")

In [47]:
c.outputs

[<tf.Tensor 'vs_layer1/var3/read:0' shape=(2,) dtype=int32>]

In [49]:
d = g0.get_operation_by_name("vs_layer1/var3")

In [50]:
d.outputs

[<tf.Tensor 'vs_layer1/var3:0' shape=(2,) dtype=int32_ref>]

In [54]:
d.type

u'VariableV2'

In [57]:
g0.finalized

False

In [67]:
var1

<tf.Variable 'var1:0' shape=(1,) dtype=float32_ref>

In [68]:
var1.op

<tf.Operation 'var1' type=VariableV2>

In [ ]:
##################################

In [74]:
g1 = tf.Graph()
with g1.as_default():
    t1 = tf.constant([1], dtype=tf.float32)
    var1 = tf.get_variable("var1", dtype=tf.float32, shape=[1], initializer=tf.zeros_initializer)
    with g1.name_scope("outer1") as scope1:
        t2 = tf.constant([1], dtype=tf.float32)
        var2 = tf.get_variable("var2", dtype=tf.float32, shape=[1], initializer=tf.zeros_initializer)
        print tf.get_variable_scope().name
    with tf.variable_scope("outer2") as scope:
        t3 = tf.constant([1], dtype=tf.float32)
        var3 = tf.get_variable("var3", dtype=tf.float32, shape=[1], initializer=tf.zeros_initializer)
        print tf.get_variable_scope().name
    


outer2


In [73]:
scope.name

'outer2'

In [65]:
g1, g0, tf.get_default_graph()

(<tensorflow.python.framework.ops.Graph at 0x7f437f4eb290>,
 <tensorflow.python.framework.ops.Graph at 0x7f437f53e690>)

In [61]:
t1.graph

In [62]:
t10 = tf.constant([1], dtype=tf.float32)

In [64]:
t10.graph

In [66]:
g1.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'var1/Initializer/zeros' type=Const>,
 <tf.Operation 'var1' type=VariableV2>,
 <tf.Operation 'var1/Assign' type=Assign>,
 <tf.Operation 'var1/read' type=Identity>,
 <tf.Operation 'outer1/Const' type=Const>,
 <tf.Operation 'var2/Initializer/zeros' type=Const>,
 <tf.Operation 'var2' type=VariableV2>,
 <tf.Operation 'var2/Assign' type=Assign>,
 <tf.Operation 'var2/read' type=Identity>]

In [ ]:
##################################

In [75]:
# 考察 会话

In [76]:
s1 = tf.Session(config=config)

In [77]:
s2 = tf.Session(config=config)

In [79]:
s3 = tf.Session(config=config, graph=g1)

In [81]:
s1, s2, s1.graph, s2.graph, s3.graph, g0, g1

(<tensorflow.python.client.session.Session at 0x7f437f53e5d0>,
 <tensorflow.python.framework.ops.Graph at 0x7f437f44ecd0>)

In [83]:
s3.run(var1.initializer)

In [85]:
s3.run(var1)

array([0.], dtype=float32)

In [87]:
##################################

In [47]:
# 考察 summary 和 visualizing

In [48]:
tf.reset_default_graph()

In [49]:
x = tf.placeholder(dtype=tf.float32, shape=[None, 784])
y_ = tf.placeholder(dtype=tf.float32, shape=[None, 10])
w = tf.get_variable("w", dtype=tf.float32, shape=[784, 10], initializer=tf.zeros_initializer)
b = tf.get_variable("b", dtype=tf.float32, shape=[10], initializer=tf.zeros_initializer)
y = tf.matmul(x,w) + b
loss = tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y)

In [50]:
a = tf.summary.scalar("mean_w", tf.reduce_mean(w))
b = tf.summary.histogram("hist_w", w)

In [51]:
a,b

(<tf.Tensor 'mean_w:0' shape=() dtype=string>,
 <tf.Tensor 'hist_w:0' shape=() dtype=string>)

In [52]:
wrt = tf.summary.FileWriter("./train", tf.get_default_graph())

In [87]:
##################################

In [515]:
tf.reset_default_graph()

In [516]:
# about variable
v1 = tf.get_variable("v1", shape=[3], initializer=tf.zeros_initializer)
inc_v1 = v1.assign(v1+1)
with tf.Session() as sess:
    v1.initializer.run()
    print v1.eval()
    print sess.run(inc_v1)
    print sess.run(v1)

[0. 0. 0.]
[1. 1. 1.]
[1. 1. 1.]


In [517]:
##################################

In [518]:
# 考察 save 和 restore

In [520]:
#-----------------------------------
# Saver.save, save的创建之前必须创建了某些tensor， 否则会出错

In [17]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [18]:
with tf.Session(config=config) as sess:
#     saver = tf.train.Saver()
    
    v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
    inc_v1 = v1.assign(v1+1)
    
    saver = tf.train.Saver()
    
    v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer)
    dec_v2 = v2.assign(v2-1)
    
    init_op = tf.global_variables_initializer()
    
    v1.initializer.run()
    v2.initializer.run()
    
    print(inc_v1.op.run(), v1.eval())
    print(dec_v2.op.run(), v2.eval())
    # Save the variables to disk.
    save_path = saver.save(sess, "./train/model.ckpt")
    print("Model saved in file: %s" % save_path)
    

(None, array([1., 1., 1.], dtype=float32))
(None, array([-1., -1., -1., -1., -1.], dtype=float32))
Model saved in file: ./train/model.ckpt


In [19]:
g0.get_operations()

[<tf.Operation 'v1/Initializer/zeros' type=Const>,
 <tf.Operation 'v1' type=VariableV2>,
 <tf.Operation 'v1/Assign' type=Assign>,
 <tf.Operation 'v1/read' type=Identity>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'save/Const' type=Const>,
 <tf.Operation 'save/SaveV2/tensor_names' type=Const>,
 <tf.Operation 'save/SaveV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/SaveV2' type=SaveV2>,
 <tf.Operation 'save/control_dependency' type=Identity>,
 <tf.Operation 'save/RestoreV2/tensor_names' type=Const>,
 <tf.Operation 'save/RestoreV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/RestoreV2' type=RestoreV2>,
 <tf.Operation 'save/Assign' type=Assign>,
 <tf.Operation 'save/restore_all' type=NoOp>,
 <tf.Operation 'v2/Initializer/zeros' type=Const>,
 <tf.Operation 'v2' type=VariableV2>,
 <tf.Operation 'v2/Assign' type=Assign>,
 <tf.Operation 'v2/read' type=Identity>,
 <tf.Operation 'sub/y' type=Const>,
 <t

In [20]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [21]:
with tf.Session(config=config) as sess:
    saver = tf.train.import_meta_graph("./train/model.ckpt.meta")

In [22]:
g0.get_operations()

[<tf.Operation 'v1/Initializer/zeros' type=Const>,
 <tf.Operation 'v1' type=VariableV2>,
 <tf.Operation 'v1/Assign' type=Assign>,
 <tf.Operation 'v1/read' type=Identity>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'save/Const' type=Const>,
 <tf.Operation 'save/SaveV2/tensor_names' type=Const>,
 <tf.Operation 'save/SaveV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/SaveV2' type=SaveV2>,
 <tf.Operation 'save/control_dependency' type=Identity>,
 <tf.Operation 'save/RestoreV2/tensor_names' type=Const>,
 <tf.Operation 'save/RestoreV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/RestoreV2' type=RestoreV2>,
 <tf.Operation 'save/Assign' type=Assign>,
 <tf.Operation 'save/restore_all' type=NoOp>,
 <tf.Operation 'v2/Initializer/zeros' type=Const>,
 <tf.Operation 'v2' type=VariableV2>,
 <tf.Operation 'v2/Assign' type=Assign>,
 <tf.Operation 'v2/read' type=Identity>,
 <tf.Operation 'sub/y' type=Const>,
 <t

In [95]:
#-----------------------------------
# Saver.save 考察global_step

In [106]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [107]:
v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
inc_v1 = v1.assign(v1+1)
inc_v11 = v1.assign_add([1,1,1])

v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer, trainable=False)
dec_v2 = v2.assign(v2-1)
dec_v21 = v2.assign_sub([1,1,1,1,1])

gs = tf.get_variable("global_step", shape=[], initializer=tf.zeros_initializer, trainable=False)
gs_add = gs.assign(gs+1)
gs_add1 = gs.assign_add(1)

# g0.add_to_collection("global", global_step)
# g0.add_to_collection("global", global_step_add)

In [111]:
with tf.Session(config=config) as sess:
    saver = tf.train.Saver()
    
    v1.initializer.run()
    v2.initializer.run()
    gs.initializer.run()
    
    for i in range(8):
        print(sess.run(inc_v1))
        print(sess.run([v1, gs]))
        
        save_path = saver.save(sess, "./train/model.ckpt", global_step=gs_add1, )  # 这一步会改变gs, 先改变gs，然后用gs命名模型文件
        
#         print("Model saved in file: %s" % save_path)

[1. 1. 1.]
[array([1., 1., 1.], dtype=float32), 0.0]
[2. 2. 2.]
[array([2., 2., 2.], dtype=float32), 1.0]
[3. 3. 3.]
[array([3., 3., 3.], dtype=float32), 2.0]
[4. 4. 4.]
[array([4., 4., 4.], dtype=float32), 3.0]
[5. 5. 5.]
[array([5., 5., 5.], dtype=float32), 4.0]
[6. 6. 6.]
[array([6., 6., 6.], dtype=float32), 5.0]
[7. 7. 7.]
[array([7., 7., 7.], dtype=float32), 6.0]
[8. 8. 8.]
[array([8., 8., 8.], dtype=float32), 7.0]


In [13]:
g0.collections

['global',
 'variables',
 ('__variable_store',),
 ('__varscope',),
 'trainable_variables']

In [77]:
g0.get_collection("variables"), g0.get_collection("trainable_variables"), g0.get_collection("global")

([<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>,
  <tf.Variable 'v2:0' shape=(5,) dtype=float32_ref>,
  <tf.Variable 'global_step:0' shape=() dtype=float32_ref>],
 [<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>],
 [])

In [94]:
g1 = tf.Graph()
with g1.as_default():
    with tf.Session(config=config) as sess:
        saver1 = tf.train.import_meta_graph("./train/model.ckpt-5.meta")
        saver1.restore(sess, "./train/model.ckpt-5")
        
#         varss = g1.get_collection("trainable_variables")
#         print sess.run(varss)

        varss1 = g1.get_collection("variables")
        print sess.run(varss1)
        
#         saver1.save(sess, "./train/model.ckpt", global_step=varss1)
        
#         varss2 = g1.get_collection("global")
#         print sess.run(varss2)


INFO:tensorflow:Restoring parameters from ./train/model.ckpt-5
[array([5., 5., 5.], dtype=float32), array([0., 0., 0., 0., 0.], dtype=float32), 5.0]


TypeError: int() argument must be a string or a number, not 'list'

In [122]:
g1 = tf.Graph()
with g1.as_default():
    v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
    inc_v1 = v1.assign(v1+1)
    inc_v11 = v1.assign_add([1,1,1])

    v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer, trainable=False)
    dec_v2 = v2.assign(v2-1)
    dec_v21 = v2.assign_sub([1,1,1,1,1])

    gs = tf.get_variable("global_step", shape=[], initializer=tf.zeros_initializer, trainable=False)
    gs_add = gs.assign(gs+1)
    gs_add1 = gs.assign_add(1)
    
    with tf.Session(config=config) as sess:
        saver = tf.train.Saver()
        saver.restore(sess, "./train/model.ckpt-10")
                
        print(sess.run([v1, gs]))
        print(sess.run(inc_v1))
        print(sess.run([v1, gs]))
        save_path = saver.save(sess, "./train/model.ckpt", global_step=gs_add1)
#         saver.save()
        

INFO:tensorflow:Restoring parameters from ./train/model.ckpt-10
[array([10., 10., 10.], dtype=float32), 10.0]
[11. 11. 11.]
[array([11., 11., 11.], dtype=float32), 10.0]


In [667]:
g1.get_operations()

[<tf.Operation 'v1/Initializer/zeros' type=Const>,
 <tf.Operation 'v1' type=VariableV2>,
 <tf.Operation 'v1/Assign' type=Assign>,
 <tf.Operation 'v1/read' type=Identity>,
 <tf.Operation 'v2/Initializer/zeros' type=Const>,
 <tf.Operation 'v2' type=VariableV2>,
 <tf.Operation 'v2/Assign' type=Assign>,
 <tf.Operation 'v2/read' type=Identity>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'sub/y' type=Const>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'Assign_1' type=Assign>,
 <tf.Operation 'save/Const' type=Const>,
 <tf.Operation 'save/SaveV2/tensor_names' type=Const>,
 <tf.Operation 'save/SaveV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/SaveV2' type=SaveV2>,
 <tf.Operation 'save/control_dependency' type=Identity>,
 <tf.Operation 'save/RestoreV2/tensor_names' type=Const>,
 <tf.Operation 'save/RestoreV2/shape_and_slices' type=Const>,
 <tf.Operation 'save/RestoreV2' type=RestoreV2>,
 <tf.Operation 'save

In [670]:
g1.get_operation_by_name("global_step/initial_value").outputs

[<tf.Tensor 'global_step/initial_value:0' shape=() dtype=int32>]

In [659]:
g1.collections

[u'variables', u'trainable_variables']

In [675]:
g1.get_collection(u"variables"), g1.get_collection(u"trainable_variables")

([<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>,
  <tf.Variable 'v2:0' shape=(5,) dtype=float32_ref>,
  <tf.Variable 'global_step:0' shape=() dtype=int32_ref>],
 [<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>,
  <tf.Variable 'v2:0' shape=(5,) dtype=float32_ref>])

In [616]:
g0.get_collection("variables"), g0.get_collection("trainable_variables")

([<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>,
  <tf.Variable 'v2:0' shape=(5,) dtype=float32_ref>,
  <tf.Variable 'global_step:0' shape=() dtype=int32_ref>],
 [<tf.Variable 'v1:0' shape=(3,) dtype=float32_ref>,
  <tf.Variable 'v2:0' shape=(5,) dtype=float32_ref>])

In [527]:
#-----------------------------------
# Saver.save 所有的

In [23]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [24]:
# Create some variables.
v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer)

inc_v1 = v1.assign(v1+1)
dec_v2 = v2.assign(v2-1)

In [25]:
# Add an op to initialize the variables.
# init_op = tf.global_variables_initializer()

# Add ops to save and restore all the variables.
# saver = tf.train.Saver()
# Later, launch the model, initialize the variables, do some work, and save the
# variables to disk.
with tf.Session() as sess:
#     sess.run(init_op)
    saver = tf.train.Saver()
    v1.initializer.run()
    v2.initializer.run()
    # Do some work with the model.
    print(inc_v1.op.run(), v1.eval())
    print(dec_v2.op.run(), v2.eval())
    # Save the variables to disk.
    save_path = saver.save(sess, "./train/model.ckpt")
    print("Model saved in file: %s" % save_path)
    print(inc_v1.op.run(), v1.eval())
    print(dec_v2.op.run(), v2.eval())

(None, array([1., 1., 1.], dtype=float32))
(None, array([-1., -1., -1., -1., -1.], dtype=float32))
Model saved in file: ./train/model.ckpt
(None, array([2., 2., 2.], dtype=float32))
(None, array([-2., -2., -2., -2., -2.], dtype=float32))


In [26]:
#-----------------------------------
# Saver.restore 所有的

In [27]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [28]:
# Create some variables.
v1 = tf.get_variable("v1", shape=[3])
v2 = tf.get_variable("v2", shape=[5])

In [29]:
# Later, launch the model, use the saver to restore variables from disk, and
# do some work with the model.
with tf.Session() as sess:
    # Restore variables from disk.
    # Add ops to save and restore all the variables.
    saver = tf.train.Saver()
    saver.restore(sess, "./train/model.ckpt")
    print("Model restored.")
    # Check the values of the variables
    sess.run([v1, v2])
    print("v1 : %s" % v1.eval())
    print("v2 : %s" % v2.eval())

INFO:tensorflow:Restoring parameters from ./train/model.ckpt
Model restored.
v1 : [1. 1. 1.]
v2 : [-1. -1. -1. -1. -1.]


In [634]:
#-----------------------------------
# 1. Saver.restore, 是恢复所有的数据，restore之后，变量都不用初始化了
# 2. import_meta_graph，只是导入图的结构（即包含哪些operation及其依赖关系，哪些collection），可以不用实现创建容器以容纳恢复的数据
# 3. import_meta_graph.restore,

In [30]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [31]:
with tf.Session() as sess:
    saver1 = tf.train.import_meta_graph("./train/model.ckpt.meta")
    saver1.restore(sess, "./train/model.ckpt")
    varss = g0.get_collection("trainable_variables")
    print sess.run(varss)

INFO:tensorflow:Restoring parameters from ./train/model.ckpt
[array([1., 1., 1.], dtype=float32), array([-1., -1., -1., -1., -1.], dtype=float32)]


In [ ]:
#-----------------------------------
#Saver.restore 所有的，但是不事先创建已知的变量，会出错，
#restore之前，必须实现知道要创建一些怎样的变量，作为容器，容纳恢复出来的数据

In [32]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [33]:
# Later, launch the model, use the saver to restore variables from disk, and
# do some work with the model.
with tf.Session() as sess:
    # Restore variables from disk.
    # Add ops to save and restore all the variables.
    saver = tf.train.Saver()
    saver.restore(sess, "./train/model.ckpt")
    print("Model restored.")
    # Check the values of the variables
#     print("v1 : %s" % v1.eval())
#     print("v2 : %s" % v2.eval())

ValueError: No variables to save

In [ ]:
#-----------------------------------
#Saver.save 部分

In [186]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [187]:
# Create some variables.
v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer)

inc_v1 = v1.assign(v1+1)
dec_v2 = v2.assign(v2-1)

# Add an op to initialize the variables.
# init_op = tf.global_variables_initializer()


# Later, launch the model, initialize the variables, do some work, and save the
# variables to disk.
with tf.Session() as sess:
#     sess.run(init_op)
    # Add ops to save and restore all the variables.
    saver = tf.train.Saver([v2])
    v1.initializer.run()
    v2.initializer.run()
    # Do some work with the model.
    inc_v1.op.run()
    dec_v2.op.run()
    # Save the variables to disk.
    save_path = saver.save(sess, "./train/model.ckpt")
    print("Model saved in file: %s" % save_path)

Model saved in file: ./train/model.ckpt


In [201]:
#-----------------------------------
#Saver.restore 部分

In [202]:
tf.reset_default_graph(); g0 = tf.get_default_graph()

In [203]:
# Create some variables.
# v1 = tf.get_variable("v1", shape=[3])
v2 = tf.get_variable("v2", shape=[5])

In [204]:
# Later, launch the model, use the saver to restore variables from disk, and
# do some work with the model.
with tf.Session() as sess:
    # Restore variables from disk.
    # Add ops to save and restore all the variables.
    saver = tf.train.Saver({"v2": v2})

#     v1.initializer.run()
    saver.restore(sess, "./train/model.ckpt")
    print("Model restored.")
    # Check the values of the variables
#     print("v1 : %s" % v1.eval())
    print("v2 : %s" % v2.eval())

INFO:tensorflow:Restoring parameters from ./train/model.ckpt
Model restored.
v2 : [-1. -1. -1. -1. -1.]


In [ ]:
##################################

In [ ]:
# softmax_cross_entropy VS sparse_softmax_cross_ectropy
y  = tf.constant([[3,1,2],[2,3,1],[1,2,3]], dtype=tf.float32)
y_ = tf.constant([[1,0,0],[0,0,1],[0,0,1]], dtype=tf.float32)
y_1 = tf.constant([0,2,2], dtype=tf.int32)
cs = tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y)
cs_1 = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y_1, logits=y)

In [ ]:
cs.eval(), cs_1.eval()

In [ ]:
-np.log(np.e**3/(np.e+np.e**2+np.e**3))

In [ ]:
# about tensor
my_matrix = tf.constant([[1,2],[3,4]], dtype=tf.int32)

In [ ]:
my_matrix_01 = my_matrix[0,1]
my_matrix_0x = my_matrix[0,:]
my_matrix_x0 = my_matrix[:,0]
my_matrix_0x_v1 = my_matrix[0:1, :]

In [ ]:
my_matrix_01, my_matrix_0x, my_matrix_x0, my_matrix_0x_v1

In [ ]:
tf.reset_default_graph()

In [ ]:
# about variable
my_local = tf.get_variable("my_local", shape=(), collections=[tf.GraphKeys.LOCAL_VARIABLES])
my_local1 = tf.get_variable("my_local1", shape=(), collections=[tf.GraphKeys.TRAINABLE_VARIABLES])
my_non_trainable = tf.get_variable("my_non_trainable", shape=(), trainable=False)

In [ ]:
my_local.graph, tf.get_default_graph()

In [ ]:
tf.GraphKeys.GLOBAL_VARIABLES, tf.GraphKeys.LOCAL_VARIABLES, tf.GraphKeys.TRAINABLE_VARIABLES

In [ ]:
tf.add_to_collection("my_collection", my_local)
tf.add_to_collection("my_collection", my_local1)
tf.add_to_collection("my_collection", my_non_trainable)

In [ ]:
tf.get_collection("my_collection")

In [ ]:
tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES), tf.get_collection(tf.GraphKeys.LOCAL_VARIABLES), tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)

In [ ]:
tf.get_collection(tf.GraphKeys.VARIABLES)

In [ ]:
g = tf.get_default_graph()

In [ ]:
g

In [ ]:
a = tf.constant([[1,2],[2,3]], dtype=tf.float32)

In [ ]:
b = tf.matmul(a,a)

In [ ]:
d = b

In [ ]:
c = tf.matmul(a,a)

In [ ]:
a,b,c, d

In [ ]:
with tf.name_scope("fasf"):
    b = tf.constant([1], dtype=tf.float32, name="ans")
    c = tf.get_variable("c", dtype=tf.float32, shape=[], initializer=tf.zeros_initializer)

In [ ]:
b

In [ ]:
c

In [ ]:
c = tf.constant([1], dtype=tf.float32, name="ans")

In [ ]:
c

In [ ]:
b,c

In [ ]:
type(tf.flags)

In [ ]:
a = tf.placeholder(dtype=tf.float32,)

In [ ]:
a

In [ ]:
b = tf.Operation()

In [ ]:
type(tf.Graph),type(tf.GraphKeys),type(tf.GraphOptions),type(tf.GraphDef)

In [ ]:
a = tf.GraphOptions()

In [ ]:
b = tf.GraphDef()

In [ ]:
b?